# Generated by Django 3.1.1 on 2020-09-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docker',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
