# Generated by Django 3.1.1 on 2020-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200922_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='command',
            field=models.TextField(default='echo helloworld'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docker',
            name='ContainerName',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
